#!/bin/sh
# rcrsn51 2010-02-13
# this script uses the additional program partclone.extfs
### Spanish translate nilsonmorales

echo
echo Este programa Respaldará/Restaruará una partición EXT.
echo Correr este script desde dentro de la partición donde será guardada el archivo de imágen.
echo La partición EXT NO debe estar montada.
echo Si usted desea sobre-escribir un archvo de imágen existente, deberá borrarlo primero.
echo

echo Hay dos operaciones: c-crear una imágen y r-restaurar una imágen
echo Un ejemplo de partición EXT sería: sda2
echo Un ejemplo de archivo de imágen seria: dogfixer.egno

echo
echo -n "Operación: [c/r] "
read OP
echo -n "Partición EXT: "
read PART
echo -n "Nomre del archivo de Imágen: "
read FILE
echo -n "Está seguro? [y/n] "
read REPLY
if [ "$REPLY" != "y" ]; then
  echo
  exit
fi

if [ "$OP" = "r" ]; then
  echo -n "Está transfiriendo la imágen a una partición diferente? [y/n] "
  read TRANS
fi

echo
echo Revisando ...
echo

fdisk -l | grep $PART | grep -q -e "Linux"
if [ $? -ne 0 ]; then
  echo Partición $PART no es EXT!
  echo
  exit
fi

mount | grep -q -e $PART
if [ $? -eq 0 ]; then
  echo Desmontar partición $PART primero!
  echo
  exit
fi

if [ $OP = "c" ] && [ -f $FILE ]; then
  echo Archivo de imágen $FILE ya existe - borrela primero!
  echo
  exit
fi

if [ $OP = "r" ] && [ ! -f $FILE ]; then
  echo Archivo de imágen $FILE no encontrada!
  echo
  exit
fi

if [ "$OP" = "c" ]; then
  e2fsck /dev/$PART
  ./gnocode/partclone.extfs -c -s /dev/$PART | gzip -c > $FILE
elif [ "$OP" = "r" ]; then
  zcat $FILE | ./gnocode/partclone.extfs -r -o /dev/$PART
  e2fsck -f /dev/$PART
fi

if [ $? -ne 0 ]; then
  echo
  exit
fi

sync

if [ "$TRANS" = "y" ]; then
  resize2fs /dev/$PART        #expand the filesystem to fill the new partition
fi

sync
echo
