#!/bin/sh
# rcrsn51 2010-04-02
# this script uses the additional programs partclone.ntfsfixboot and ms-sys 
## Spanish translate nilsonmorales

echo
echo Este programa respaldará/restaurará una partición NTFST.
echo Corra este script desde dentro de la particion donde el archivo de imágen se halla guardado.
echo la partición NTFS no debe estar montada.
echo Si desea sobre-escribir una archivo de imagen existente, debe borrarla primero.
echo

echo Hay dos operaciones: c-crear una imágen y r-restaurar una imágen
echo La partición NTFS probablemente es: sda1
echo Un ejemplo de archivo de imágen es: winxp.gno
echo

echo -n "Operación: [c/r] "
read OP
echo -n "Partición NTFS: "
read PART
echo -n "Nombre de archivo de imágen: "
read FILE
echo -n "Está seguro? [y/n] "
read REPLY
if [ "$REPLY" != "y" ]; then
  echo
  exit
fi

if [ "$OP" = "r" ]; then
  echo -n "Está transfiriendo la imágen a un disco duro diferente? [y/n] "
  read TRANS
fi

echo
echo Revisando ...
echo

fdisk -l | grep $PART | grep -q -e "NTFS"
if [ $? -ne 0 ]; then
  echo Partición $PART no es NTFS!
  echo
  exit
fi

mount | grep -q -e $PART
if [ $? -eq 0 ]; then
  echo Desmontar partición $PART primero!
  echo
  exit
fi

if [ "$OP" = "c" ] && [ -f $FILE ]; then
  echo Archivo de imágen $FILE ya existe - borrelo primero!
  echo
  exit
fi

if [ "$OP" = "r" ] && [ ! -f $FILE ]; then
  echo Archivo de imágen $FILE no se encuentra!
  echo
  exit
fi

if [ "$OP" = "c" ]; then
  ntfsclone --save-image --output - /dev/$PART | gzip -c > $FILE
elif [ "$OP" = "r" ]; then
  zcat $FILE | ntfsclone --restore-image --overwrite /dev/$PART -
fi

if [ $? -ne 0 ]; then
  echo
  exit
fi

sync

if [ "$TRANS" = "y" ]; then
  echo "y" | ntfsresize /dev/$PART        #expand the filesystem to fill the new partition
  ./gnocode/partclone.ntfsfixboot -w /dev/$PART   #update the boot sector to match the new drive geometry
  DRV=${PART:0:3}
  dd if=/dev/zero of=/dev/$DRV bs=446 count=1 #erase the old volume ID
  ms-sys --mbr --write /dev/$DRV            #write a standard DOS/Win MBR to the drive
fi

if [ "$OP" = "r" ]; then
  ntfsfix /dev/$PART			  #schedule a Windows CHKDSK on reboot
fi  

sync
echo
