#!/bin/sh
tail -n +4 $0 > /tmp/myscript.txt
exec roxterm -e sh /tmp/myscript.txt

PWD=`pwd`

xmessage -buttons 1:0,2:1,3:2,4:3,5:4,6:5,7:6,Quit:7 "Run this program from inside the partition holding 
the image files.

Current directory: $PWD
 
1: Backup/restore an NTFS partition
2: Copy an NTFS partition
3: Backup/restore an EXT partition
4: Copy an EXT partition
5: Backup/restore a FAT partition
6: Copy a FAT partition
7: Save drive information to a file
"

case $? in
0) ./gnocode/gnost;;
1) ./gnocode/gnoclone;;
2) ./gnocode/egnost;;
3) ./gnocode/egnoclone;;
4) ./gnocode/fgnost;;
5) ./gnocode/fgnoclone;;
6) ./gnocode/driveinfo;;
7) ;;
esac
read -p "Press Enter: "
