#!/bin/sh
# nilsonmorales


export TEXTDOMAIN=gnostmenu
export OUTPUT_CHARSET=UTF-8
B_OK="GTK_STOCK_OK"

Xdialog --title "$(gettext 'GNOSTMENU')" --screen-center --left --menubox "$(gettext 'Clone/restore NTFS, EXT, FAT partitions')" 320x220 10 \
 '1' "$(gettext 'Backup/restore an NTFS partition')" \
 '2' "$(gettext 'Copy an NTFS partition')" \
 '3' "$(gettext 'Backup/restore an EXT partition')" \
 '4' "$(gettext 'Copy a EXT partition')" \
 '5' "$(gettext 'Backup/restore a FAT partition')" \
 '6' "$(gettext 'Copy a FAT partition')" \
 '7' "$(gettext 'Save drive information to a file')" \
2>/tmp/myscript.tmp

r=`tail -n 1 /tmp/myscript.tmp`

if [ "$r" == "1" ];then
   roxterm -e ./gnocode/gnost
   exit ## Exit Script ##
fi

if [ "$r" == "2" ];then
   roxterm -e ./gnocode/gnoclone
   exit ## Exit Script ##
fi

if [ "$r" == "3" ];then
   roxterm -e ./gnocode/egnost
   exit ## Exit Script ##
fi

if [ "$r" == "4" ];then
   roxterm -e ./gnocode/egnoclone
   exit ## Exit Script ##
fi

if [ "$r" == "5" ];then
   roxterm -e ./gnocode/fgnost 
   exit ## Exit Script ##
fi

if [ "$r" == "6" ];then
   roxterm -e ./gnocode/fgnoclone
   exit ## Exit Script ##
fi

if [ "$r" == "7" ];then
   roxterm -e ./gnocode/driveinfo
   exit ## Exit Script ##
fi

exit # END SCRIPT #

















